package geo

type place struct {
	city    string
	country string
}

// regionalCodes covers the 2-letter "regional" 1e100.net prefixes documented
// on the wiki. This list is necessarily incomplete -- Google does not publish
// it, so entries are added as they're observed in the wild.
var regionalCodes = map[string]place{
	"bc": {"Washington, VA", "United States"},
	"bg": {"Washington, VA", "United States"},
	"bh": {"Washington, VA", "United States"},
	"bi": {"Washington, VA", "United States"},
	"bj": {"Washington, VA", "United States"},
	"bk": {"Washington, VA", "United States"},
	"bl": {"Washington, VA", "United States"},
	"bt": {"Frankfurt am Main", "Germany"},
	"bu": {"Melbourne", "Australia"},
	"bv": {"Melbourne", "Australia"},
	"bw": {"Melbourne", "Australia"},
	"bx": {"Frankfurt am Main", "Germany"},
	"by": {"Frankfurt am Main", "Germany"},
	"bz": {"Frankfurt am Main", "Germany"},
	"cb": {"Santiago", "Chile"},
	"ce": {"Santiago", "Chile"},
	"cf": {"Santiago", "Chile"},
	"cg": {"Santiago", "Chile"},
	"cj": {"Santiago", "Chile"},
	"cm": {"Mumbai", "India"},
	"cn": {"Mumbai", "India"},
	"co": {"Santiago", "Chile"},
	"cu": {"Milan", "Italy"},
	"cv": {"Milan", "Italy"},
	"cw": {"Milan", "Italy"},
	"cx": {"Turin", "Italy"},
	"cy": {"Turin", "Italy"},
	"cz": {"Turin", "Italy"},
	"dd": {"Las Vegas, NV", "United States"},
	"dg": {"Dublin", "Ireland"},
	"dh": {"Dublin", "Ireland"},
	"di": {"Dublin", "Ireland"},
	"dj": {"Dublin", "Ireland"},
	"dl": {"Las Vegas, NV", "United States"},
	"dx": {"Mumbai", "India"},
	"dy": {"Las Vegas, NV", "United States"},
	"dz": {"Las Vegas, NV", "United States"},
	"ea": {"Groningen", "Netherlands"},
	"eb": {"Groningen", "Netherlands"},
	"ec": {"Groningen", "Netherlands"},
	"ed": {"Groningen", "Netherlands"},
	"ef": {"Groningen", "Netherlands"},
	"eg": {"Groningen", "Netherlands"},
	"eh": {"Groningen", "Netherlands"},
	"ei": {"Groningen", "Netherlands"},
	"ej": {"Groningen", "Netherlands"},
	"el": {"Groningen", "Netherlands"},
	"en": {"Groningen", "Netherlands"},
	"eq": {"Groningen", "Netherlands"},
	"er": {"Groningen", "Netherlands"},
	"et": {"Madrid", "Spain"},
	"eu": {"Madrid", "Spain"},
	"ev": {"Madrid", "Spain"},
	"ew": {"Madrid", "Spain"},
	"fb": {"Seoul", "South Korea"},
	"fc": {"Seoul", "South Korea"},
	"ff": {"Seoul", "South Korea"},
	"fg": {"Seoul", "South Korea"},
	"fh": {"Jakarta", "Indonesia"},
	"fi": {"Jakarta", "Indonesia"},
	"fj": {"Jakarta", "Indonesia"},
	"fk": {"Jakarta", "Indonesia"},
	"fl": {"Washington, VA", "United States"},
	"fm": {"Washington, VA", "United States"},
	"fn": {"Washington, VA", "United States"},
	"fo": {"Jakarta", "Indonesia"},
	"fq": {"Sydney", "Australia"},
	"fr": {"Sydney", "Australia"},
	"fs": {"Frankfurt am Main", "Germany"},
	"ft": {"São Paulo", "Brazil"},
	"fu": {"São Paulo", "Brazil"},
	"fv": {"São Paulo", "Brazil"},
	"fw": {"Mumbai", "India"},
	"fx": {"Mumbai", "India"},
	"fy": {"Mumbai", "India"},
	"ga": {"Columbus, OH", "United States"},
	"gb": {"Columbus, OH", "United States"},
	"gc": {"Sewanee, TN", "United States"},
	"gd": {"Sewanee, TN", "United States"},
	"ge": {"Sewanee, TN", "United States"},
	"gf": {"Atlanta, GA", "United States"},
	"gg": {"Atlanta, GA", "United States"},
	"gh": {"Columbus, OH", "United States"},
	"gi": {"Atlanta, GA", "United States"},
	"gj": {"Atlanta, GA", "United States"},
	"gk": {"Atlanta, GA", "United States"},
	"gl": {"Columbus, OH", "United States"},
	"gm": {"Columbus, OH", "United States"},
	"go": {"Columbus, OH", "United States"},
	"gq": {"Sydney", "Australia"},
	"gv": {"Tel Aviv", "Israel"},
	"ha": {"Mumbai", "India"},
	"hb": {"Mumbai", "India"},
	"hc": {"Mumbai", "India"},
	"hd": {"Montréal", "Canada"},
	"he": {"Montréal", "Canada"},
	"hf": {"Montréal", "Canada"},
	"hh": {"Los Angeles, CA", "United States"},
	"hi": {"Los Angeles, CA", "United States"},
	"hj": {"Hong Kong", "Hong Kong"},
	"hk": {"Hong Kong", "Hong Kong"},
	"hl": {"Hong Kong", "Hong Kong"},
	"hm": {"Los Angeles, CA", "United States"},
	"ho": {"Los Angeles, CA", "United States"},
	"hq": {"Osaka", "Japan"},
	"hr": {"Osaka", "Japan"},
	"hs": {"Osaka", "Japan"},
	"hw": {"Zürich", "Switzerland"},
	"hx": {"Zürich", "Switzerland"},
	"hy": {"Zürich", "Switzerland"},
	"hz": {"Paris", "France"},
	"ia": {"Council Bluffs, IA", "United States"},
	"ib": {"Council Bluffs, IA", "United States"},
	"ic": {"Council Bluffs, IA", "United States"},
	"ie": {"Council Bluffs, IA", "United States"},
	"if": {"Council Bluffs, IA", "United States"},
	"ig": {"Council Bluffs, IA", "United States"},
	"ii": {"Zürich", "Switzerland"},
	"il": {"Council Bluffs, IA", "United States"},
	"im": {"Council Bluffs, IA", "United States"},
	"in": {"Council Bluffs, IA", "United States"},
	"io": {"Council Bluffs, IA", "United States"},
	"iq": {"Council Bluffs, IA", "United States"},
	"ir": {"Council Bluffs, IA", "United States"},
	"is": {"Council Bluffs, IA", "United States"},
	"it": {"Council Bluffs, IA", "United States"},
	"iu": {"Council Bluffs, IA", "United States"},
	"iv": {"Council Bluffs, IA", "United States"},
	"iw": {"Council Bluffs, IA", "United States"},
	"ix": {"Council Bluffs, IA", "United States"},
	"iy": {"Council Bluffs, IA", "United States"},
	"iz": {"Council Bluffs, IA", "United States"},
	"ja": {"Council Bluffs, IA", "United States"},
	"jb": {"Council Bluffs, IA", "United States"},
	"jc": {"Council Bluffs, IA", "United States"},
	"jd": {"Council Bluffs, IA", "United States"},
	"je": {"Council Bluffs, IA", "United States"},
	"jf": {"Council Bluffs, IA", "United States"},
	"jg": {"Council Bluffs, IA", "United States"},
	"jh": {"Council Bluffs, IA", "United States"},
	"ji": {"Council Bluffs, IA", "United States"},
	"jj": {"Council Bluffs, IA", "United States"},
	"jl": {"Council Bluffs, IA", "United States"},
	"jn": {"Council Bluffs, IA", "United States"},
	"jo": {"Council Bluffs, IA", "United States"},
	"jp": {"Council Bluffs, IA", "United States"},
	"jq": {"Council Bluffs, IA", "United States"},
	"jr": {"Council Bluffs, IA", "United States"},
	"js": {"Council Bluffs, IA", "United States"},
	"jv": {"Council Bluffs, IA", "United States"},
	"jw": {"Council Bluffs, IA", "United States"},
	"jx": {"Council Bluffs, IA", "United States"},
	"jy": {"Council Bluffs, IA", "United States"},
	"kz": {"Zürich", "Switzerland"},
	"la": {"Lappeenranta", "Finland"},
	"lb": {"Lappeenranta", "Finland"},
	"le": {"Lappeenranta", "Finland"},
	"lf": {"Lappeenranta", "Finland"},
	"lg": {"Lappeenranta", "Finland"},
	"lh": {"Lappeenranta", "Finland"},
	"li": {"Lappeenranta", "Finland"},
	"lj": {"Lappeenranta", "Finland"},
	"lk": {"Lappeenranta", "Finland"},
	"lm": {"Lappeenranta", "Finland"},
	"lo": {"Lappeenranta", "Finland"},
	"lq": {"Lappeenranta", "Finland"},
	"lr": {"Lappeenranta", "Finland"},
	"lt": {"Lappeenranta", "Finland"},
	"lu": {"Lappeenranta", "Finland"},
	"lx": {"Tel Aviv", "Israel"},
	"ly": {"Mumbai", "India"},
	"lz": {"Mumbai", "India"},
	"ma": {"Clarksville, TN", "United States"},
	"mb": {"Clarksville, TN", "United States"},
	"md": {"Clarksville, TN", "United States"},
	"me": {"Clarksville, TN", "United States"},
	"mf": {"Clarksville, TN", "United States"},
	"mg": {"Clarksville, TN", "United States"},
	"mh": {"Clarksville, TN", "United States"},
	"mj": {"Clarksville, TN", "United States"},
	"mr": {"Salt Lake City, UT", "United States"},
	"mu": {"Milan", "Italy"},
	"my": {"Mumbai", "India"},
	"na": {"Tulsa, OK", "United States"},
	"nb": {"Tulsa, OK", "United States"},
	"nd": {"Tulsa, OK", "United States"},
	"ne": {"Tulsa, OK", "United States"},
	"nf": {"Tulsa, OK", "United States"},
	"ng": {"Tulsa, OK", "United States"},
	"nh": {"Tel Aviv", "Israel"},
	"nj": {"Tulsa, OK", "United States"},
	"nk": {"Tulsa, OK", "United States"},
	"nl": {"Tulsa, OK", "United States"},
	"nm": {"Tulsa, OK", "United States"},
	"nn": {"Tulsa, OK", "United States"},
	"nq": {"Hong Kong", "Hong Kong"},
	"nr": {"Santiago", "Chile"},
	"nt": {"Warsaw", "Poland"},
	"nu": {"Delhi", "India"},
	"nv": {"Delhi", "India"},
	"nw": {"Delhi", "India"},
	"nx": {"Tel Aviv", "Israel"},
	"ny": {"Council Bluffs, IA", "United States"},
	"nz": {"Council Bluffs, IA", "United States"},
	"oa": {"Tulsa, OK", "United States"},
	"ob": {"Tulsa, OK", "United States"},
	"oc": {"Tulsa, OK", "United States"},
	"od": {"Tulsa, OK", "United States"},
	"oe": {"Tulsa, OK", "United States"},
	"og": {"Tulsa, OK", "United States"},
	"oi": {"Tulsa, OK", "United States"},
	"oj": {"Tulsa, OK", "United States"},
	"ok": {"Tulsa, OK", "United States"},
	"oo": {"Tulsa, OK", "United States"},
	"oq": {"Tulsa, OK", "United States"},
	"or": {"Tulsa, OK", "United States"},
	"os": {"Tulsa, OK", "United States"},
	"ot": {"Tulsa, OK", "United States"},
	"ou": {"Tulsa, OK", "United States"},
	"ov": {"Tulsa, OK", "United States"},
	"ow": {"Tulsa, OK", "United States"},
	"ox": {"Tulsa, OK", "United States"},
	"oy": {"Tulsa, OK", "United States"},
	"oz": {"Tulsa, OK", "United States"},
	"pa": {"Tulsa, OK", "United States"},
	"pb": {"Tulsa, OK", "United States"},
	"pd": {"Washington, VA", "United States"},
	"pe": {"Washington, VA", "United States"},
	"pf": {"The Dalles, OR", "United States"},
	"pg": {"The Dalles, OR", "United States"},
	"ph": {"The Dalles, OR", "United States"},
	"pi": {"The Dalles, OR", "United States"},
	"pj": {"The Dalles, OR", "United States"},
	"pl": {"The Dalles, OR", "United States"},
	"pm": {"Frankfurt am Main", "Germany"},
	"pt": {"Mumbai", "India"},
	"pu": {"Mumbai", "India"},
	"pv": {"The Dalles, OR", "United States"},
	"pw": {"The Dalles, OR", "United States"},
	"px": {"The Dalles, OR", "United States"},
	"py": {"The Dalles, OR", "United States"},
	"pz": {"The Dalles, OR", "United States"},
	"qa": {"Morganton, NC", "United States"},
	"qb": {"Morganton, NC", "United States"},
	"qc": {"Morganton, NC", "United States"},
	"qf": {"Salt Lake City, UT", "United States"},
	"qg": {"Morganton, NC", "United States"},
	"qh": {"Columbus, OH", "United States"},
	"qi": {"Morganton, NC", "United States"},
	"qk": {"Morganton, NC", "United States"},
	"qm": {"Morganton, NC", "United States"},
	"qn": {"Morganton, NC", "United States"},
	"qo": {"Morganton, NC", "United States"},
	"qr": {"Morganton, NC", "United States"},
	"qs": {"Morganton, NC", "United States"},
	"qt": {"Morganton, NC", "United States"},
	"qu": {"Morganton, NC", "United States"},
	"qv": {"Morganton, NC", "United States"},
	"qw": {"Columbus, OH", "United States"},
	"qy": {"Salt Lake City, UT", "United States"},
	"ra": {"Den Helder", "Netherlands"},
	"rb": {"Den Helder", "Netherlands"},
	"rc": {"Billund", "Denmark"},
	"rd": {"Billund", "Denmark"},
	"rf": {"Paris", "France"},
	"rg": {"Columbus, OH", "United States"},
	"rj": {"Tokyo", "Japan"},
	"rk": {"Tokyo", "Japan"},
	"rl": {"Tokyo", "Japan"},
	"ro": {"Reno, NV", "United States"},
	"rq": {"Dallas, TX", "United States"},
	"rr": {"Dallas, TX", "United States"},
	"rs": {"Dallas, TX", "United States"},
	"rt": {"Dallas, TX", "United States"},
	"ru": {"Reno, NV", "United States"},
	"rv": {"Reno, NV", "United States"},
	"rw": {"Dallas, TX", "United States"},
	"rx": {"Tokyo", "Japan"},
	"ry": {"Washington, VA", "United States"},
	"rz": {"Washington, VA", "United States"},
	"sa": {"Singapore", "Singapore"},
	"sb": {"Singapore", "Singapore"},
	"sc": {"Singapore", "Singapore"},
	"sd": {"Singapore", "Singapore"},
	"se": {"Singapore", "Singapore"},
	"sf": {"Singapore", "Singapore"},
	"sg": {"Singapore", "Singapore"},
	"sh": {"Singapore", "Singapore"},
	"si": {"Singapore", "Singapore"},
	"sj": {"Singapore", "Singapore"},
	"sk": {"Singapore", "Singapore"},
	"sl": {"Singapore", "Singapore"},
	"sm": {"Singapore", "Singapore"},
	"sn": {"Singapore", "Singapore"},
	"so": {"Singapore", "Singapore"},
	"sq": {"Jakarta", "Indonesia"},
	"sr": {"Jakarta", "Indonesia"},
	"st": {"London", "United Kingdom"},
	"sv": {"London", "United Kingdom"},
	"sx": {"Singapore", "Singapore"},
	"sy": {"Singapore", "Singapore"},
	"ta": {"Taipei", "Taiwan"},
	"tb": {"Taipei", "Taiwan"},
	"tc": {"Taipei", "Taiwan"},
	"td": {"Taipei", "Taiwan"},
	"tf": {"Taipei", "Taiwan"},
	"tg": {"Taipei", "Taiwan"},
	"th": {"Taipei", "Taiwan"},
	"ti": {"Taipei", "Taiwan"},
	"tj": {"Taipei", "Taiwan"},
	"tk": {"Taipei", "Taiwan"},
	"tl": {"Taipei", "Taiwan"},
	"tm": {"Taipei", "Taiwan"},
	"tp": {"Taipei", "Taiwan"},
	"ts": {"The Dalles, OR", "United States"},
	"tt": {"The Dalles, OR", "United States"},
	"tu": {"Osaka", "Japan"},
	"tv": {"Osaka", "Japan"},
	"tw": {"Doha", "Qatar"},
	"tx": {"Doha", "Qatar"},
	"ty": {"Doha", "Qatar"},
	"ua": {"Charleston, SC", "United States"},
	"ub": {"Charleston, SC", "United States"},
	"uc": {"Charleston, SC", "United States"},
	"ud": {"Charleston, SC", "United States"},
	"ue": {"Charleston, SC", "United States"},
	"uf": {"Charleston, SC", "United States"},
	"ug": {"Charleston, SC", "United States"},
	"uh": {"Charleston, SC", "United States"},
	"ui": {"Charleston, SC", "United States"},
	"uj": {"Charleston, SC", "United States"},
	"uk": {"Charleston, SC", "United States"},
	"ul": {"London", "United Kingdom"},
	"um": {"London", "United Kingdom"},
	"uo": {"London", "United Kingdom"},
	"uv": {"London", "United Kingdom"},
	"ux": {"Charleston, SC", "United States"},
	"uy": {"Charleston, SC", "United States"},
	"vb": {"Charleston, SC", "United States"},
	"vc": {"Berlin", "Germany"},
	"vd": {"Berlin", "Germany"},
	"vj": {"Charleston, SC", "United States"},
	"vk": {"Charleston, SC", "United States"},
	"vl": {"Charleston, SC", "United States"},
	"vn": {"Charleston, SC", "United States"},
	"vo": {"Charleston, SC", "United States"},
	"vq": {"Charleston, SC", "United States"},
	"vr": {"Charleston, SC", "United States"},
	"vs": {"Charleston, SC", "United States"},
	"vt": {"Charleston, SC", "United States"},
	"vu": {"Charleston, SC", "United States"},
	"vw": {"Charleston, SC", "United States"},
	"vx": {"Charleston, SC", "United States"},
	"vz": {"Charleston, SC", "United States"},
	"wa": {"Brussels", "Belgium"},
	"wb": {"Brussels", "Belgium"},
	"wd": {"Brussels", "Belgium"},
	"we": {"Brussels", "Belgium"},
	"wf": {"Brussels", "Belgium"},
	"wg": {"Brussels", "Belgium"},
	"wh": {"Brussels", "Belgium"},
	"wi": {"Brussels", "Belgium"},
	"wj": {"London", "United Kingdom"},
	"wk": {"Brussels", "Belgium"},
	"wl": {"Brussels", "Belgium"},
	"wm": {"Brussels", "Belgium"},
	"wn": {"Brussels", "Belgium"},
	"wo": {"Brussels", "Belgium"},
	"wq": {"Brussels", "Belgium"},
	"wr": {"Brussels", "Belgium"},
	"ws": {"Brussels", "Belgium"},
	"wt": {"Frankfurt am Main", "Germany"},
	"wu": {"Seoul", "South Korea"},
	"wv": {"Washington, VA", "United States"},
	"ww": {"Washington, VA", "United States"},
	"wx": {"Turin", "Italy"},
	"wy": {"Turin", "Italy"},
	"wz": {"Turin", "Italy"},
	"xa": {"Tokyo", "Japan"},
	"xb": {"Tokyo", "Japan"},
	"xc": {"Tokyo", "Japan"},
	"xd": {"London", "United Kingdom"},
	"xe": {"London", "United Kingdom"},
	"xf": {"London", "United Kingdom"},
	"xg": {"Washington, VA", "United States"},
	"xh": {"Washington, VA", "United States"},
	"xi": {"Washington, VA", "United States"},
	"xj": {"Frankfurt am Main", "Germany"},
	"xk": {"Frankfurt am Main", "Germany"},
	"xm": {"Frankfurt am Main", "Germany"},
	"xn": {"Sydney", "Australia"},
	"xo": {"Sydney", "Australia"},
	"xq": {"Sydney", "Australia"},
	"xu": {"São Paulo", "Brazil"},
	"xv": {"São Paulo", "Brazil"},
	"xw": {"São Paulo", "Brazil"},
	"xy": {"Frankfurt am Main", "Germany"},
	"xz": {"Tokyo", "Japan"},
	"ya": {"Atlanta, GA", "United States"},
	"yb": {"Atlanta, GA", "United States"},
	"yd": {"Paris", "France"},
	"ye": {"Paris", "France"},
	"yi": {"Atlanta, GA", "United States"},
	"yj": {"Berlin", "Germany"},
	"yl": {"Atlanta, GA", "United States"},
	"ym": {"Atlanta, GA", "United States"},
	"yo": {"Atlanta, GA", "United States"},
	"yq": {"Atlanta, GA", "United States"},
	"yr": {"Atlanta, GA", "United States"},
	"ys": {"Atlanta, GA", "United States"},
	"yt": {"Atlanta, GA", "United States"},
	"yv": {"Atlanta, GA", "United States"},
	"yw": {"Atlanta, GA", "United States"},
	"yx": {"Atlanta, GA", "United States"},
	"zd": {"Salt Lake City, UT", "United States"},
	"ze": {"Salt Lake City, UT", "United States"},
	"zf": {"Salt Lake City, UT", "United States"},
	"zg": {"Tokyo", "Japan"},
	"zh": {"Tokyo", "Japan"},
	"zi": {"Hong Kong", "Hong Kong"},
	"zj": {"Tokyo", "Japan"},
	"zk": {"Las Vegas, NV", "United States"},
	"zl": {"Las Vegas, NV", "United States"},
	"zm": {"Las Vegas, NV", "United States"},
	"zo": {"Warsaw", "Poland"},
	"zq": {"Warsaw", "Poland"},
	"zr": {"Warsaw", "Poland"},
	"zs": {"Frankfurt am Main", "Germany"},
	"zt": {"Frankfurt am Main", "Germany"},
	"zu": {"Frankfurt am Main", "Germany"},
	"zv": {"Frankfurt am Main", "Germany"},
}

// airportCodes maps IATA airport codes to the city/country Google's PTR
// naming convention associates them with. This is a best-effort table of
// airports known to host Google infrastructure (from public reporting and
// community documentation) plus common major-airport codes as a fallback --
// an unrecognized code simply renders without a resolved location.
var airportCodes = map[string]place{
	// United States
	"atl": {"Atlanta, GA", "United States"},
	"auz": {"Aurora, IL", "United States"},
	"bos": {"Boston, MA", "United States"},
	"cbf": {"Council Bluffs, IA", "United States"},
	"clt": {"Charlotte, NC", "United States"},
	"den": {"Denver, CO", "United States"},
	"dfw": {"Dallas-Fort Worth, TX", "United States"},
	"dls": {"The Dalles, OR", "United States"},
	"ewr": {"Newark, NJ", "United States"},
	"hou": {"Houston, TX", "United States"},
	"iad": {"Ashburn/Washington, VA", "United States"},
	"iah": {"Houston, TX", "United States"},
	"jfk": {"New York, NY", "United States"},
	"las": {"Las Vegas, NV", "United States"},
	"lax": {"Los Angeles, CA", "United States"},
	"lga": {"New York, NY", "United States"},
	"lhm": {"Council Bluffs, IA", "United States"},
	"mci": {"Kansas City, MO", "United States"},
	"mia": {"Miami, FL", "United States"},
	"msp": {"Minneapolis, MN", "United States"},
	"nuq": {"Mountain View, CA", "United States"},
	"oak": {"Oakland, CA", "United States"},
	"okc": {"Oklahoma City, OK", "United States"},
	"ord": {"Chicago, IL", "United States"},
	"pao": {"Palo Alto, CA", "United States"},
	"pdx": {"Portland, OR", "United States"},
	"phx": {"Phoenix, AZ", "United States"},
	"rfd": {"Rockford, IL", "United States"},
	"rno": {"Reno, NV", "United States"},
	"sea": {"Seattle, WA", "United States"},
	"sfo": {"San Francisco, CA", "United States"},
	"sjc": {"San Jose, CA", "United States"},
	"slc": {"Salt Lake City, UT", "United States"},
	"stl": {"St. Louis, MO", "United States"},
	"uos": {"Franklin County, TN", "United States"},

	// Canada
	"yyz": {"Toronto", "Canada"},

	// Europe
	"ams": {"Amsterdam/Eemshaven", "Netherlands"},
	"arn": {"Stockholm", "Sweden"},
	"ber": {"Berlin", "Germany"},
	"bud": {"Budapest", "Hungary"},
	"buh": {"Bucharest", "Romania"},
	"cdg": {"Paris", "France"},
	"cph": {"Copenhagen", "Denmark"},
	"dub": {"Dublin", "Ireland"},
	"fco": {"Rome", "Italy"},
	"fra": {"Frankfurt", "Germany"},
	"gro": {"Girona/Barcelona", "Spain"},
	"ham": {"Hamburg", "Germany"},
	"hel": {"Hamina/Helsinki", "Finland"},
	"lcy": {"London", "United Kingdom"},
	"lhr": {"London", "United Kingdom"},
	"lis": {"Lisbon", "Portugal"},
	"mad": {"Madrid", "Spain"},
	"man": {"Manchester", "United Kingdom"},
	"mil": {"Milan", "Italy"},
	"mrs": {"Marseille", "France"},
	"muc": {"Munich", "Germany"},
	"mxp": {"Milan", "Italy"},
	"ork": {"Cork", "Ireland"},
	"osl": {"Oslo", "Norway"},
	"otp": {"Bucharest", "Romania"},
	"par": {"Paris", "France"},
	"prg": {"Prague", "Czechia"},
	"ske": {"Skien", "Norway"},
	"sof": {"Sofia", "Bulgaria"},
	"vie": {"Vienna", "Austria"},
	"waw": {"Warsaw", "Poland"},
	"zrh": {"Zurich", "Switzerland"},

	// Asia-Pacific
	"akl": {"Auckland", "New Zealand"},
	"bkk": {"Bangkok", "Thailand"},
	"blr": {"Bengaluru", "India"},
	"bom": {"Mumbai", "India"},
	"cgk": {"Jakarta", "Indonesia"},
	"del": {"Delhi", "India"},
	"gmp": {"Seoul", "South Korea"},
	"hkg": {"Hong Kong", "Hong Kong"},
	"hnd": {"Tokyo", "Japan"},
	"hyd": {"Hyderabad", "India"},
	"icn": {"Seoul", "South Korea"},
	"kix": {"Osaka", "Japan"},
	"kul": {"Kuala Lumpur", "Malaysia"},
	"maa": {"Chennai", "India"},
	"mel": {"Melbourne", "Australia"},
	"mnl": {"Manila", "Philippines"},
	"nrt": {"Tokyo", "Japan"},
	"pek": {"Beijing", "China"},
	"per": {"Perth", "Australia"},
	"pnq": {"Pune", "India"},
	"sha": {"Shanghai", "China"},
	"sin": {"Singapore", "Singapore"},
	"syd": {"Sydney", "Australia"},
	"tsa": {"Taipei", "Taiwan"},

	// Latin America
	"bog": {"Bogotá", "Colombia"},
	"eze": {"Buenos Aires", "Argentina"},
	"gig": {"Rio de Janeiro", "Brazil"},
	"gru": {"São Paulo", "Brazil"},
	"lim": {"Lima", "Peru"},
	"mex": {"Mexico City", "Mexico"},
	"qro": {"Querétaro", "Mexico"},
	"scl": {"Santiago", "Chile"},

	// Middle East / Africa
	"cai": {"Cairo", "Egypt"},
	"doh": {"Doha", "Qatar"},
	"dxb": {"Dubai", "United Arab Emirates"},
	"jnb": {"Johannesburg", "South Africa"},
	"mba": {"Mombasa", "Kenya"},
	"tlv": {"Tel Aviv", "Israel"},
}
