// Generated from internal/geo/airports.go by a one-off conversion script -- do not hand-edit.
// Regenerate by re-running the script against the Go source if airports.go changes.
export interface Place {
	city: string;
	country: string;
}

// regionalCodes covers the 2-letter "regional" 1e100.net prefixes documented
// on the wiki. This list is necessarily incomplete -- Google does not publish
// it, so entries are added as they're observed in the wild.
export const regionalCodes: Record<string, Place> = {
	"bc": { city: "Washington, VA", country: "United States" },
	"bg": { city: "Washington, VA", country: "United States" },
	"bh": { city: "Washington, VA", country: "United States" },
	"bi": { city: "Washington, VA", country: "United States" },
	"bj": { city: "Washington, VA", country: "United States" },
	"bk": { city: "Washington, VA", country: "United States" },
	"bl": { city: "Washington, VA", country: "United States" },
	"bt": { city: "Frankfurt am Main", country: "Germany" },
	"bu": { city: "Melbourne", country: "Australia" },
	"bv": { city: "Melbourne", country: "Australia" },
	"bw": { city: "Melbourne", country: "Australia" },
	"bx": { city: "Frankfurt am Main", country: "Germany" },
	"by": { city: "Frankfurt am Main", country: "Germany" },
	"bz": { city: "Frankfurt am Main", country: "Germany" },
	"cb": { city: "Santiago", country: "Chile" },
	"ce": { city: "Santiago", country: "Chile" },
	"cf": { city: "Santiago", country: "Chile" },
	"cg": { city: "Santiago", country: "Chile" },
	"cj": { city: "Santiago", country: "Chile" },
	"cm": { city: "Mumbai", country: "India" },
	"cn": { city: "Mumbai", country: "India" },
	"co": { city: "Santiago", country: "Chile" },
	"cu": { city: "Milan", country: "Italy" },
	"cv": { city: "Milan", country: "Italy" },
	"cw": { city: "Milan", country: "Italy" },
	"dd": { city: "Las Vegas, NV", country: "United States" },
	"dg": { city: "Dublin", country: "Ireland" },
	"dh": { city: "Dublin", country: "Ireland" },
	"di": { city: "Dublin", country: "Ireland" },
	"dj": { city: "Dublin", country: "Ireland" },
	"dl": { city: "Las Vegas, NV", country: "United States" },
	"dx": { city: "Mumbai", country: "India" },
	"dy": { city: "Las Vegas, NV", country: "United States" },
	"dz": { city: "Las Vegas, NV", country: "United States" },
	"ea": { city: "Groningen", country: "Netherlands" },
	"eb": { city: "Groningen", country: "Netherlands" },
	"ec": { city: "Groningen", country: "Netherlands" },
	"ed": { city: "Groningen", country: "Netherlands" },
	"ef": { city: "Groningen", country: "Netherlands" },
	"eg": { city: "Groningen", country: "Netherlands" },
	"eh": { city: "Groningen", country: "Netherlands" },
	"ei": { city: "Groningen", country: "Netherlands" },
	"ej": { city: "Groningen", country: "Netherlands" },
	"el": { city: "Groningen", country: "Netherlands" },
	"en": { city: "Groningen", country: "Netherlands" },
	"eq": { city: "Groningen", country: "Netherlands" },
	"er": { city: "Groningen", country: "Netherlands" },
	"et": { city: "Madrid", country: "Spain" },
	"eu": { city: "Madrid", country: "Spain" },
	"ev": { city: "Madrid", country: "Spain" },
	"ew": { city: "Madrid", country: "Spain" },
	"fb": { city: "Seoul", country: "South Korea" },
	"fc": { city: "Seoul", country: "South Korea" },
	"ff": { city: "Seoul", country: "South Korea" },
	"fg": { city: "Seoul", country: "South Korea" },
	"fh": { city: "Jakarta", country: "Indonesia" },
	"fi": { city: "Jakarta", country: "Indonesia" },
	"fj": { city: "Jakarta", country: "Indonesia" },
	"fk": { city: "Jakarta", country: "Indonesia" },
	"fl": { city: "Washington, VA", country: "United States" },
	"fm": { city: "Washington, VA", country: "United States" },
	"fn": { city: "Washington, VA", country: "United States" },
	"fo": { city: "Jakarta", country: "Indonesia" },
	"fq": { city: "Sydney", country: "Australia" },
	"fr": { city: "Sydney", country: "Australia" },
	"fs": { city: "Frankfurt am Main", country: "Germany" },
	"ft": { city: "São Paulo", country: "Brazil" },
	"fu": { city: "São Paulo", country: "Brazil" },
	"fv": { city: "São Paulo", country: "Brazil" },
	"fw": { city: "Mumbai", country: "India" },
	"fx": { city: "Mumbai", country: "India" },
	"fy": { city: "Mumbai", country: "India" },
	"ga": { city: "Columbus, OH", country: "United States" },
	"gb": { city: "Columbus, OH", country: "United States" },
	"gc": { city: "Sewanee, TN", country: "United States" },
	"gd": { city: "Sewanee, TN", country: "United States" },
	"ge": { city: "Sewanee, TN", country: "United States" },
	"gf": { city: "Atlanta, GA", country: "United States" },
	"gg": { city: "Atlanta, GA", country: "United States" },
	"gh": { city: "Columbus, OH", country: "United States" },
	"gi": { city: "Atlanta, GA", country: "United States" },
	"gj": { city: "Atlanta, GA", country: "United States" },
	"gk": { city: "Atlanta, GA", country: "United States" },
	"gl": { city: "Columbus, OH", country: "United States" },
	"gm": { city: "Columbus, OH", country: "United States" },
	"go": { city: "Columbus, OH", country: "United States" },
	"gq": { city: "Sydney", country: "Australia" },
	"gv": { city: "Tel Aviv", country: "Israel" },
	"ha": { city: "Mumbai", country: "India" },
	"hb": { city: "Mumbai", country: "India" },
	"hc": { city: "Mumbai", country: "India" },
	"hd": { city: "Montréal", country: "Canada" },
	"he": { city: "Montréal", country: "Canada" },
	"hf": { city: "Montréal", country: "Canada" },
	"hh": { city: "Los Angeles, CA", country: "United States" },
	"hi": { city: "Los Angeles, CA", country: "United States" },
	"hj": { city: "Hong Kong", country: "Hong Kong" },
	"hk": { city: "Hong Kong", country: "Hong Kong" },
	"hl": { city: "Hong Kong", country: "Hong Kong" },
	"hm": { city: "Los Angeles, CA", country: "United States" },
	"ho": { city: "Los Angeles, CA", country: "United States" },
	"hq": { city: "Osaka", country: "Japan" },
	"hr": { city: "Osaka", country: "Japan" },
	"hs": { city: "Osaka", country: "Japan" },
	"hw": { city: "Zürich", country: "Switzerland" },
	"hx": { city: "Zürich", country: "Switzerland" },
	"hy": { city: "Zürich", country: "Switzerland" },
	"hz": { city: "Paris", country: "France" },
	"ia": { city: "Council Bluffs, IA", country: "United States" },
	"ib": { city: "Council Bluffs, IA", country: "United States" },
	"ic": { city: "Council Bluffs, IA", country: "United States" },
	"ie": { city: "Council Bluffs, IA", country: "United States" },
	"if": { city: "Council Bluffs, IA", country: "United States" },
	"ig": { city: "Council Bluffs, IA", country: "United States" },
	"ii": { city: "Zürich", country: "Switzerland" },
	"il": { city: "Council Bluffs, IA", country: "United States" },
	"im": { city: "Council Bluffs, IA", country: "United States" },
	"in": { city: "Council Bluffs, IA", country: "United States" },
	"io": { city: "Council Bluffs, IA", country: "United States" },
	"iq": { city: "Council Bluffs, IA", country: "United States" },
	"ir": { city: "Council Bluffs, IA", country: "United States" },
	"is": { city: "Council Bluffs, IA", country: "United States" },
	"it": { city: "Council Bluffs, IA", country: "United States" },
	"iu": { city: "Council Bluffs, IA", country: "United States" },
	"iv": { city: "Council Bluffs, IA", country: "United States" },
	"iw": { city: "Council Bluffs, IA", country: "United States" },
	"ix": { city: "Council Bluffs, IA", country: "United States" },
	"iy": { city: "Council Bluffs, IA", country: "United States" },
	"iz": { city: "Council Bluffs, IA", country: "United States" },
	"ja": { city: "Council Bluffs, IA", country: "United States" },
	"jb": { city: "Council Bluffs, IA", country: "United States" },
	"jc": { city: "Council Bluffs, IA", country: "United States" },
	"jd": { city: "Council Bluffs, IA", country: "United States" },
	"je": { city: "Council Bluffs, IA", country: "United States" },
	"jf": { city: "Council Bluffs, IA", country: "United States" },
	"jg": { city: "Council Bluffs, IA", country: "United States" },
	"jh": { city: "Council Bluffs, IA", country: "United States" },
	"ji": { city: "Council Bluffs, IA", country: "United States" },
	"jj": { city: "Council Bluffs, IA", country: "United States" },
	"jl": { city: "Council Bluffs, IA", country: "United States" },
	"jn": { city: "Council Bluffs, IA", country: "United States" },
	"jo": { city: "Council Bluffs, IA", country: "United States" },
	"jp": { city: "Council Bluffs, IA", country: "United States" },
	"jq": { city: "Council Bluffs, IA", country: "United States" },
	"jr": { city: "Council Bluffs, IA", country: "United States" },
	"js": { city: "Council Bluffs, IA", country: "United States" },
	"jv": { city: "Council Bluffs, IA", country: "United States" },
	"jw": { city: "Council Bluffs, IA", country: "United States" },
	"jx": { city: "Council Bluffs, IA", country: "United States" },
	"jy": { city: "Council Bluffs, IA", country: "United States" },
	"kz": { city: "Zürich", country: "Switzerland" },
	"la": { city: "Lappeenranta", country: "Finland" },
	"lb": { city: "Lappeenranta", country: "Finland" },
	"le": { city: "Lappeenranta", country: "Finland" },
	"lf": { city: "Lappeenranta", country: "Finland" },
	"lg": { city: "Lappeenranta", country: "Finland" },
	"lh": { city: "Lappeenranta", country: "Finland" },
	"li": { city: "Lappeenranta", country: "Finland" },
	"lj": { city: "Lappeenranta", country: "Finland" },
	"lk": { city: "Lappeenranta", country: "Finland" },
	"lm": { city: "Lappeenranta", country: "Finland" },
	"lo": { city: "Lappeenranta", country: "Finland" },
	"lq": { city: "Lappeenranta", country: "Finland" },
	"lr": { city: "Lappeenranta", country: "Finland" },
	"lt": { city: "Lappeenranta", country: "Finland" },
	"lu": { city: "Lappeenranta", country: "Finland" },
	"lx": { city: "Tel Aviv", country: "Israel" },
	"ly": { city: "Mumbai", country: "India" },
	"ma": { city: "Clarksville, TN", country: "United States" },
	"mb": { city: "Clarksville, TN", country: "United States" },
	"md": { city: "Clarksville, TN", country: "United States" },
	"me": { city: "Clarksville, TN", country: "United States" },
	"mf": { city: "Clarksville, TN", country: "United States" },
	"mg": { city: "Clarksville, TN", country: "United States" },
	"mh": { city: "Clarksville, TN", country: "United States" },
	"mj": { city: "Clarksville, TN", country: "United States" },
	"mr": { city: "Salt Lake City, UT", country: "United States" },
	"mu": { city: "Milan", country: "Italy" },
	"my": { city: "Mumbai", country: "India" },
	"na": { city: "Tulsa, OK", country: "United States" },
	"nb": { city: "Tulsa, OK", country: "United States" },
	"nd": { city: "Tulsa, OK", country: "United States" },
	"ne": { city: "Tulsa, OK", country: "United States" },
	"nf": { city: "Tulsa, OK", country: "United States" },
	"ng": { city: "Tulsa, OK", country: "United States" },
	"nh": { city: "Tel Aviv", country: "Israel" },
	"nj": { city: "Tulsa, OK", country: "United States" },
	"nk": { city: "Tulsa, OK", country: "United States" },
	"nl": { city: "Tulsa, OK", country: "United States" },
	"nm": { city: "Tulsa, OK", country: "United States" },
	"nn": { city: "Tulsa, OK", country: "United States" },
	"nq": { city: "Hong Kong", country: "Hong Kong" },
	"nr": { city: "Santiago", country: "Chile" },
	"nt": { city: "Warsaw", country: "Poland" },
	"nu": { city: "Delhi", country: "India" },
	"nv": { city: "Delhi", country: "India" },
	"nw": { city: "Delhi", country: "India" },
	"nx": { city: "Tel Aviv", country: "Israel" },
	"ny": { city: "Council Bluffs, IA", country: "United States" },
	"nz": { city: "Council Bluffs, IA", country: "United States" },
	"oa": { city: "Tulsa, OK", country: "United States" },
	"ob": { city: "Tulsa, OK", country: "United States" },
	"oc": { city: "Tulsa, OK", country: "United States" },
	"od": { city: "Tulsa, OK", country: "United States" },
	"oe": { city: "Tulsa, OK", country: "United States" },
	"og": { city: "Tulsa, OK", country: "United States" },
	"oi": { city: "Tulsa, OK", country: "United States" },
	"oj": { city: "Tulsa, OK", country: "United States" },
	"ok": { city: "Tulsa, OK", country: "United States" },
	"oo": { city: "Tulsa, OK", country: "United States" },
	"oq": { city: "Tulsa, OK", country: "United States" },
	"or": { city: "Tulsa, OK", country: "United States" },
	"os": { city: "Tulsa, OK", country: "United States" },
	"ot": { city: "Tulsa, OK", country: "United States" },
	"ou": { city: "Tulsa, OK", country: "United States" },
	"ov": { city: "Tulsa, OK", country: "United States" },
	"ow": { city: "Tulsa, OK", country: "United States" },
	"ox": { city: "Tulsa, OK", country: "United States" },
	"oy": { city: "Tulsa, OK", country: "United States" },
	"oz": { city: "Tulsa, OK", country: "United States" },
	"pa": { city: "Tulsa, OK", country: "United States" },
	"pb": { city: "Tulsa, OK", country: "United States" },
	"pd": { city: "Washington, VA", country: "United States" },
	"pe": { city: "Washington, VA", country: "United States" },
	"pf": { city: "The Dalles, OR", country: "United States" },
	"pg": { city: "The Dalles, OR", country: "United States" },
	"ph": { city: "The Dalles, OR", country: "United States" },
	"pi": { city: "The Dalles, OR", country: "United States" },
	"pj": { city: "The Dalles, OR", country: "United States" },
	"pl": { city: "The Dalles, OR", country: "United States" },
	"pm": { city: "Frankfurt am Main", country: "Germany" },
	"pt": { city: "Mumbai", country: "India" },
	"pu": { city: "Mumbai", country: "India" },
	"pv": { city: "The Dalles, OR", country: "United States" },
	"pw": { city: "The Dalles, OR", country: "United States" },
	"px": { city: "The Dalles, OR", country: "United States" },
	"py": { city: "The Dalles, OR", country: "United States" },
	"pz": { city: "The Dalles, OR", country: "United States" },
	"qa": { city: "Morganton, NC", country: "United States" },
	"qb": { city: "Morganton, NC", country: "United States" },
	"qc": { city: "Morganton, NC", country: "United States" },
	"qf": { city: "Salt Lake City, UT", country: "United States" },
	"qg": { city: "Morganton, NC", country: "United States" },
	"qh": { city: "Columbus, OH", country: "United States" },
	"qi": { city: "Morganton, NC", country: "United States" },
	"qk": { city: "Morganton, NC", country: "United States" },
	"qm": { city: "Morganton, NC", country: "United States" },
	"qn": { city: "Morganton, NC", country: "United States" },
	"qo": { city: "Morganton, NC", country: "United States" },
	"qr": { city: "Morganton, NC", country: "United States" },
	"qs": { city: "Morganton, NC", country: "United States" },
	"qt": { city: "Morganton, NC", country: "United States" },
	"qu": { city: "Morganton, NC", country: "United States" },
	"qv": { city: "Morganton, NC", country: "United States" },
	"qw": { city: "Columbus, OH", country: "United States" },
	"qy": { city: "Salt Lake City, UT", country: "United States" },
	"ra": { city: "Den Helder", country: "Netherlands" },
	"rb": { city: "Den Helder", country: "Netherlands" },
	"rf": { city: "Paris", country: "France" },
	"rg": { city: "Columbus, OH", country: "United States" },
	"rj": { city: "Tokyo", country: "Japan" },
	"rk": { city: "Tokyo", country: "Japan" },
	"rl": { city: "Tokyo", country: "Japan" },
	"ro": { city: "Reno, NV", country: "United States" },
	"rq": { city: "Dallas, TX", country: "United States" },
	"rr": { city: "Dallas, TX", country: "United States" },
	"rs": { city: "Dallas, TX", country: "United States" },
	"rt": { city: "Dallas, TX", country: "United States" },
	"ru": { city: "Reno, NV", country: "United States" },
	"rv": { city: "Reno, NV", country: "United States" },
	"rw": { city: "Dallas, TX", country: "United States" },
	"rx": { city: "Tokyo", country: "Japan" },
	"ry": { city: "Washington, VA", country: "United States" },
	"rz": { city: "Washington, VA", country: "United States" },
	"sa": { city: "Singapore", country: "Singapore" },
	"sb": { city: "Singapore", country: "Singapore" },
	"sc": { city: "Singapore", country: "Singapore" },
	"sd": { city: "Singapore", country: "Singapore" },
	"se": { city: "Singapore", country: "Singapore" },
	"sf": { city: "Singapore", country: "Singapore" },
	"sg": { city: "Singapore", country: "Singapore" },
	"sh": { city: "Singapore", country: "Singapore" },
	"si": { city: "Singapore", country: "Singapore" },
	"sj": { city: "Singapore", country: "Singapore" },
	"sk": { city: "Singapore", country: "Singapore" },
	"sl": { city: "Singapore", country: "Singapore" },
	"sm": { city: "Singapore", country: "Singapore" },
	"sn": { city: "Singapore", country: "Singapore" },
	"so": { city: "Singapore", country: "Singapore" },
	"sq": { city: "Jakarta", country: "Indonesia" },
	"sr": { city: "Jakarta", country: "Indonesia" },
	"st": { city: "London", country: "United Kingdom" },
	"sv": { city: "London", country: "United Kingdom" },
	"sx": { city: "Singapore", country: "Singapore" },
	"sy": { city: "Singapore", country: "Singapore" },
	"ta": { city: "Taipei", country: "Taiwan" },
	"tb": { city: "Taipei", country: "Taiwan" },
	"tc": { city: "Taipei", country: "Taiwan" },
	"td": { city: "Taipei", country: "Taiwan" },
	"tf": { city: "Taipei", country: "Taiwan" },
	"tg": { city: "Taipei", country: "Taiwan" },
	"th": { city: "Taipei", country: "Taiwan" },
	"ti": { city: "Taipei", country: "Taiwan" },
	"tj": { city: "Taipei", country: "Taiwan" },
	"tk": { city: "Taipei", country: "Taiwan" },
	"tl": { city: "Taipei", country: "Taiwan" },
	"tm": { city: "Taipei", country: "Taiwan" },
	"tp": { city: "Taipei", country: "Taiwan" },
	"ts": { city: "The Dalles, OR", country: "United States" },
	"tt": { city: "The Dalles, OR", country: "United States" },
	"tu": { city: "Osaka", country: "Japan" },
	"tv": { city: "Osaka", country: "Japan" },
	"tw": { city: "Doha", country: "Qatar" },
	"tx": { city: "Doha", country: "Qatar" },
	"ty": { city: "Doha", country: "Qatar" },
	"ua": { city: "Charleston, SC", country: "United States" },
	"ub": { city: "Charleston, SC", country: "United States" },
	"uc": { city: "Charleston, SC", country: "United States" },
	"ud": { city: "Charleston, SC", country: "United States" },
	"ue": { city: "Charleston, SC", country: "United States" },
	"uf": { city: "Charleston, SC", country: "United States" },
	"ug": { city: "Charleston, SC", country: "United States" },
	"uh": { city: "Charleston, SC", country: "United States" },
	"ui": { city: "Charleston, SC", country: "United States" },
	"uj": { city: "Charleston, SC", country: "United States" },
	"uk": { city: "Charleston, SC", country: "United States" },
	"ul": { city: "London", country: "United Kingdom" },
	"um": { city: "London", country: "United Kingdom" },
	"uo": { city: "London", country: "United Kingdom" },
	"uv": { city: "London", country: "United Kingdom" },
	"ux": { city: "Charleston, SC", country: "United States" },
	"uy": { city: "Charleston, SC", country: "United States" },
	"vb": { city: "Charleston, SC", country: "United States" },
	"vc": { city: "Berlin", country: "Germany" },
	"vd": { city: "Berlin", country: "Germany" },
	"vj": { city: "Charleston, SC", country: "United States" },
	"vk": { city: "Charleston, SC", country: "United States" },
	"vl": { city: "Charleston, SC", country: "United States" },
	"vn": { city: "Charleston, SC", country: "United States" },
	"vo": { city: "Charleston, SC", country: "United States" },
	"vq": { city: "Charleston, SC", country: "United States" },
	"vr": { city: "Charleston, SC", country: "United States" },
	"vs": { city: "Charleston, SC", country: "United States" },
	"vt": { city: "Charleston, SC", country: "United States" },
	"vu": { city: "Charleston, SC", country: "United States" },
	"vw": { city: "Charleston, SC", country: "United States" },
	"vx": { city: "Charleston, SC", country: "United States" },
	"vz": { city: "Charleston, SC", country: "United States" },
	"wa": { city: "Brussels", country: "Belgium" },
	"wb": { city: "Brussels", country: "Belgium" },
	"wd": { city: "Brussels", country: "Belgium" },
	"we": { city: "Brussels", country: "Belgium" },
	"wf": { city: "Brussels", country: "Belgium" },
	"wg": { city: "Brussels", country: "Belgium" },
	"wh": { city: "Brussels", country: "Belgium" },
	"wi": { city: "Brussels", country: "Belgium" },
	"wj": { city: "London", country: "United Kingdom" },
	"wk": { city: "Brussels", country: "Belgium" },
	"wl": { city: "Brussels", country: "Belgium" },
	"wm": { city: "Brussels", country: "Belgium" },
	"wn": { city: "Brussels", country: "Belgium" },
	"wo": { city: "Brussels", country: "Belgium" },
	"wq": { city: "Brussels", country: "Belgium" },
	"wr": { city: "Brussels", country: "Belgium" },
	"ws": { city: "Brussels", country: "Belgium" },
	"wt": { city: "Frankfurt am Main", country: "Germany" },
	"wu": { city: "Seoul", country: "South Korea" },
	"wv": { city: "Washington, VA", country: "United States" },
	"ww": { city: "Washington, VA", country: "United States" },
	"wx": { city: "Turin", country: "Italy" },
	"wy": { city: "Turin", country: "Italy" },
	"wz": { city: "Turin", country: "Italy" },
	"xa": { city: "Tokyo", country: "Japan" },
	"xb": { city: "Tokyo", country: "Japan" },
	"xc": { city: "Tokyo", country: "Japan" },
	"xd": { city: "London", country: "United Kingdom" },
	"xe": { city: "London", country: "United Kingdom" },
	"xf": { city: "London", country: "United Kingdom" },
	"xg": { city: "Washington, VA", country: "United States" },
	"xh": { city: "Washington, VA", country: "United States" },
	"xi": { city: "Washington, VA", country: "United States" },
	"xj": { city: "Frankfurt am Main", country: "Germany" },
	"xk": { city: "Frankfurt am Main", country: "Germany" },
	"xm": { city: "Frankfurt am Main", country: "Germany" },
	"xn": { city: "Sydney", country: "Australia" },
	"xo": { city: "Sydney", country: "Australia" },
	"xq": { city: "Sydney", country: "Australia" },
	"xu": { city: "São Paulo", country: "Brazil" },
	"xv": { city: "São Paulo", country: "Brazil" },
	"xw": { city: "São Paulo", country: "Brazil" },
	"xy": { city: "Frankfurt am Main", country: "Germany" },
	"xz": { city: "Tokyo", country: "Japan" },
	"ya": { city: "Atlanta, GA", country: "United States" },
	"yb": { city: "Atlanta, GA", country: "United States" },
	"yd": { city: "Paris", country: "France" },
	"ye": { city: "Paris", country: "France" },
	"yi": { city: "Atlanta, GA", country: "United States" },
	"yj": { city: "Berlin", country: "Germany" },
	"yl": { city: "Atlanta, GA", country: "United States" },
	"ym": { city: "Atlanta, GA", country: "United States" },
	"yo": { city: "Atlanta, GA", country: "United States" },
	"yq": { city: "Atlanta, GA", country: "United States" },
	"yr": { city: "Atlanta, GA", country: "United States" },
	"ys": { city: "Atlanta, GA", country: "United States" },
	"yt": { city: "Atlanta, GA", country: "United States" },
	"yv": { city: "Atlanta, GA", country: "United States" },
	"yw": { city: "Atlanta, GA", country: "United States" },
	"yx": { city: "Atlanta, GA", country: "United States" },
	"zd": { city: "Salt Lake City, UT", country: "United States" },
	"ze": { city: "Salt Lake City, UT", country: "United States" },
	"zf": { city: "Salt Lake City, UT", country: "United States" },
	"zg": { city: "Tokyo", country: "Japan" },
	"zh": { city: "Tokyo", country: "Japan" },
	"zi": { city: "Hong Kong", country: "Hong Kong" },
	"zj": { city: "Tokyo", country: "Japan" },
	"zk": { city: "Las Vegas, NV", country: "United States" },
	"zl": { city: "Las Vegas, NV", country: "United States" },
	"zm": { city: "Las Vegas, NV", country: "United States" },
	"zo": { city: "Warsaw", country: "Poland" },
	"zq": { city: "Warsaw", country: "Poland" },
	"zr": { city: "Warsaw", country: "Poland" },
	"zs": { city: "Frankfurt am Main", country: "Germany" },
	"zt": { city: "Frankfurt am Main", country: "Germany" },
	"zu": { city: "Frankfurt am Main", country: "Germany" },
	"zv": { city: "Frankfurt am Main", country: "Germany" },
};

// airportCodes maps IATA airport codes to the city/country Google's PTR
// naming convention associates them with.
export const airportCodes: Record<string, Place> = {
	"atl": { city: "Atlanta, GA", country: "United States" },
	"auz": { city: "Aurora, IL", country: "United States" },
	"bos": { city: "Boston, MA", country: "United States" },
	"cbf": { city: "Council Bluffs, IA", country: "United States" },
	"clt": { city: "Charlotte, NC", country: "United States" },
	"cmh" :{ city: "Columbus, OH", country: "United States"},
	"den": { city: "Denver, CO", country: "United States" },
	"dfw": { city: "Dallas-Fort Worth, TX", country: "United States" },
	"dls": { city: "The Dalles, OR", country: "United States" },
	"ewr": { city: "Newark, NJ", country: "United States" },
	"hou": { city: "Houston, TX", country: "United States" },
	"iad": { city: "Ashburn/Washington, VA", country: "United States" },
	"iah": { city: "Houston, TX", country: "United States" },
	"jfk": { city: "New York, NY", country: "United States" },
	"las": { city: "Las Vegas, NV", country: "United States" },
	"lax": { city: "Los Angeles, CA", country: "United States" },
	"lga": { city: "New York, NY", country: "United States" },
	"lhm": { city: "Council Bluffs, IA", country: "United States" },
	"mci": { city: "Kansas City, MO", country: "United States" },
	"mia": { city: "Miami, FL", country: "United States" },
	"mrn": { city: "Morganton, NC", country: "United States"},
	"msp": { city: "Minneapolis, MN", country: "United States" },
	"nuq": { city: "Mountain View, CA", country: "United States" },
	"oak": { city: "Oakland, CA", country: "United States" },
	"okc": { city: "Oklahoma City, OK", country: "United States" },
	"ord": { city: "Chicago, IL", country: "United States" },
	"pao": { city: "Palo Alto, CA", country: "United States" },
	"pdx": { city: "Portland, OR", country: "United States" },
	"phx": { city: "Phoenix, AZ", country: "United States" },
	"rfd": { city: "Rockford, IL", country: "United States" },
	"rno": { city: "Reno, NV", country: "United States" },
	"sea": { city: "Seattle, WA", country: "United States" },
	"sfo": { city: "San Francisco, CA", country: "United States" },
	"sjc": { city: "San Jose, CA", country: "United States" },
	"slc": { city: "Salt Lake City, UT", country: "United States" },
	"stl": { city: "St. Louis, MO", country: "United States" },
	"uos": { city: "Franklin County, TN", country: "United States" },
	"yyz": { city: "Toronto", country: "Canada" },
	"ams": { city: "Amsterdam/Eemshaven", country: "Netherlands" },
	"arn": { city: "Stockholm", country: "Sweden" },
	"ber": { city: "Berlin", country: "Germany" },
	"bud": { city: "Budapest", country: "Hungary" },
	"buh": { city: "Bucharest", country: "Romania" },
	"cdg": { city: "Paris", country: "France" },
	"cph": { city: "Copenhagen", country: "Denmark" },
	"dub": { city: "Dublin", country: "Ireland" },
	"fco": { city: "Rome", country: "Italy" },
	"fra": { city: "Frankfurt", country: "Germany" },
	"gro": { city: "Girona/Barcelona", country: "Spain" },
	"ham": { city: "Hamburg", country: "Germany" },
	"hel": { city: "Hamina/Helsinki", country: "Finland" },
	"lcy": { city: "London", country: "United Kingdom" },
	"lhr": { city: "London", country: "United Kingdom" },
	"lis": { city: "Lisbon", country: "Portugal" },
	"mad": { city: "Madrid", country: "Spain" },
	"man": { city: "Manchester", country: "United Kingdom" },
	"mil": { city: "Milan", country: "Italy" },
	"mrs": { city: "Marseille", country: "France" },
	"muc": { city: "Munich", country: "Germany" },
	"mxp": { city: "Milan", country: "Italy" },
	"ork": { city: "Cork", country: "Ireland" },
	"osl": { city: "Oslo", country: "Norway" },
	"otp": { city: "Bucharest", country: "Romania" },
	"par": { city: "Paris", country: "France" },
	"prg": { city: "Prague", country: "Czechia" },
	"ske": { city: "Skien", country: "Norway" },
	"sof": { city: "Sofia", country: "Bulgaria" },
	"vie": { city: "Vienna", country: "Austria" },
	"waw": { city: "Warsaw", country: "Poland" },
	"zrh": { city: "Zurich", country: "Switzerland" },
	"akl": { city: "Auckland", country: "New Zealand" },
	"bkk": { city: "Bangkok", country: "Thailand" },
	"blr": { city: "Bengaluru", country: "India" },
	"bom": { city: "Mumbai", country: "India" },
	"cgk": { city: "Jakarta", country: "Indonesia" },
	"del": { city: "Delhi", country: "India" },
	"gmp": { city: "Seoul", country: "South Korea" },
	"hkg": { city: "Hong Kong", country: "Hong Kong" },
	"hnd": { city: "Tokyo", country: "Japan" },
	"hyd": { city: "Hyderabad", country: "India" },
	"icn": { city: "Seoul", country: "South Korea" },
	"kix": { city: "Osaka", country: "Japan" },
	"kul": { city: "Kuala Lumpur", country: "Malaysia" },
	"maa": { city: "Chennai", country: "India" },
	"mel": { city: "Melbourne", country: "Australia" },
	"mnl": { city: "Manila", country: "Philippines" },
	"nrt": { city: "Tokyo", country: "Japan" },
	"pek": { city: "Beijing", country: "China" },
	"per": { city: "Perth", country: "Australia" },
	"pnq": { city: "Pune", country: "India" },
	"sha": { city: "Shanghai", country: "China" },
	"sin": { city: "Singapore", country: "Singapore" },
	"syd": { city: "Sydney", country: "Australia" },
	"tsa": { city: "Taipei", country: "Taiwan" },
	"bog": { city: "Bogotá", country: "Colombia" },
	"eze": { city: "Buenos Aires", country: "Argentina" },
	"gig": { city: "Rio de Janeiro", country: "Brazil" },
	"gru": { city: "São Paulo", country: "Brazil" },
	"lim": { city: "Lima", country: "Peru" },
	"mex": { city: "Mexico City", country: "Mexico" },
	"qro": { city: "Querétaro", country: "Mexico" },
	"scl": { city: "Santiago", country: "Chile" },
	"cai": { city: "Cairo", country: "Egypt" },
	"dmm": { city: "Dammam", country: "Saudi Arabia" },
	"doh": { city: "Doha", country: "Qatar" },
	"dxb": { city: "Dubai", country: "United Arab Emirates" },
	"jnb": { city: "Johannesburg", country: "South Africa" },
	"mba": { city: "Mombasa", country: "Kenya" },
	"tlv": { city: "Tel Aviv", country: "Israel" },
};
